const { generateSlug, generateUniqueSlug } = require("./generateUniqueSlug");
const {
  normalizeFiles,
  validateFilesExist,
  countImages,
  countVideos,
  getFileNameWithoutExtension,
  validateMediaFiles,
  validateThumbnailFile,
  prepareMediaDocuments,
  getExistingMediaCounts,
  getNextMediaSortOrder,
  normalizeSortOrder,
  validateUniqueIds,
  validateUniqueSortOrders,
  getMediaCoverImage,
  pickCoverMedia,
  syncSectionCoverImage,
} = require("./validateMedia");
const {
  uploadSingleMedia,
  uploadMultipleMedia,
  rollbackUploads,
  deleteMedia,
  deleteAllMedia,
  isCustomThumbnail,
  deleteCustomThumbnail,
} = require("./upload");
const { resolveSectionForActor } = require("./resolveSectionForActor");
const {
  customerSectionMatch,
  visibleMediaCondition,
  managedMediaCondition,
  clipEligibleMediaCondition,
  sortedClipMedias,
  sortedVisibleMedias,
  countMediaOfType,
  mediaCounts,
  customerMediaFields,
  customerMediaMap,
  formatSectionSummary,
  formatManagedMedia,
} = require("./projections");

module.exports = {
  resolveSectionForActor,
  generateSlug,
  generateUniqueSlug,
  normalizeFiles,
  validateFilesExist,
  countImages,
  countVideos,
  getFileNameWithoutExtension,
  validateMediaFiles,
  validateThumbnailFile,
  prepareMediaDocuments,
  getExistingMediaCounts,
  getNextMediaSortOrder,
  normalizeSortOrder,
  validateUniqueIds,
  validateUniqueSortOrders,
  getMediaCoverImage,
  pickCoverMedia,
  syncSectionCoverImage,
  uploadSingleMedia,
  uploadMultipleMedia,
  rollbackUploads,
  deleteMedia,
  deleteAllMedia,
  isCustomThumbnail,
  deleteCustomThumbnail,
  // Shared read shapes — see projections.js
  customerSectionMatch,
  visibleMediaCondition,
  managedMediaCondition,
  clipEligibleMediaCondition,
  sortedClipMedias,
  sortedVisibleMedias,
  countMediaOfType,
  mediaCounts,
  customerMediaFields,
  customerMediaMap,
  formatSectionSummary,
  formatManagedMedia,
};
