const { generateSlug, generateUniqueSlug } = require("./generateUniqueSlug");
const {
  normalizeFiles,
  validateFilesExist,
  countImages,
  countVideos,
  getFileNameWithoutExtension,
  validateMediaFiles,
  validateThumbnailFile,
  prepareMediaDocuments,
  getExistingMediaCounts,
  getNextMediaSortOrder,
  resequenceMedias,
  normalizeSortOrder,
  validateUniqueIds,
  validateUniqueSortOrders,
  getMediaCoverImage,
  pickCoverMedia,
  syncSectionCoverImage,
} = require("./validateMedia");
const {
  uploadSingleMedia,
  uploadMultipleMedia,
  rollbackUploads,
  deleteMedia,
  deleteAllMedia,
  POSTER_FILE_FIELD,
} = require("./upload");
const { resolveSectionForActor } = require("./resolveSectionForActor");
const { resequenceSections } = require("./resequenceSections");
const {
  countVisibleMedia,
  assertSectionKeepsItsFloor,
  assertBrandKeepsASection,
  assertBrandKeepsAVisibleSection,
} = require("./guards");
const {
  customerSectionMatch,
  visibleMediaCondition,
  managedMediaCondition,
  clipEligibleMediaCondition,
  sortedClipMedias,
  sortedVisibleMedias,
  countMediaOfType,
  mediaCounts,
  customerMediaFields,
  customerMediaMap,
  formatSectionSummary,
  formatManagedMedia,
} = require("./projections");

module.exports = {
  resolveSectionForActor,
  resequenceSections,
  // Write guards — the two floors, in one place (guards.js)
  countVisibleMedia,
  assertSectionKeepsItsFloor,
  assertBrandKeepsASection,
  assertBrandKeepsAVisibleSection,
  generateSlug,
  generateUniqueSlug,
  normalizeFiles,
  validateFilesExist,
  countImages,
  countVideos,
  getFileNameWithoutExtension,
  validateMediaFiles,
  validateThumbnailFile,
  prepareMediaDocuments,
  getExistingMediaCounts,
  getNextMediaSortOrder,
  resequenceMedias,
  normalizeSortOrder,
  validateUniqueIds,
  validateUniqueSortOrders,
  getMediaCoverImage,
  pickCoverMedia,
  syncSectionCoverImage,
  uploadSingleMedia,
  uploadMultipleMedia,
  rollbackUploads,
  deleteMedia,
  deleteAllMedia,
  POSTER_FILE_FIELD,
  // Shared read shapes — see projections.js
  customerSectionMatch,
  visibleMediaCondition,
  managedMediaCondition,
  clipEligibleMediaCondition,
  sortedClipMedias,
  sortedVisibleMedias,
  countMediaOfType,
  mediaCounts,
  customerMediaFields,
  customerMediaMap,
  formatSectionSummary,
  formatManagedMedia,
};
