const Joi = require("joi");
const objectId = require("./validJoiObjectId");

exports.validateGetAllSubscribedQuery = (payload) => {
  const schema = Joi.object({
    page: Joi.number().integer().min(1).optional(),
    limit: Joi.number().integer().min(1).optional(),
    user: objectId().optional(),
    brand: objectId().optional(),
    subscribedBy: objectId().optional(),
    upgradedBy: objectId().optional(),
    transaction: objectId().optional(),
    subscription: objectId().optional(),
    upgradedTo: objectId().optional(),
    isActive: Joi.boolean().optional(),
    isExpired: Joi.boolean().optional(),
    isUpgraded: Joi.boolean().optional(),
    isCoolingPlan: Joi.boolean().optional(),
    durationInDays: Joi.number().integer().min(0).optional(),
    durationInYears: Joi.number().integer().min(0).optional(),
    price: Joi.number().integer().min(0).optional(),
    discount: Joi.number().integer().min(0).optional(),
    numberOfSubBrands: Joi.number().integer().min(0).optional(),
    paidAmount: Joi.number().integer().min(0).optional(),
    dueAmount: Joi.number().integer().min(0).optional(),
    numberOfUpgrade: Joi.number().integer().min(0).optional(),
    minDurationInDays: Joi.number().integer().min(0).optional(),
    minDurationInYears: Joi.number().integer().min(0).optional(),
    minPrice: Joi.number().integer().min(0).optional(),
    minDiscount: Joi.number().integer().min(0).optional(),
    minNumberOfSubBrands: Joi.number().integer().min(0).optional(),
    minPaidAmount: Joi.number().integer().min(0).optional(),
    minDueAmount: Joi.number().integer().min(0).optional(),
    minNumberOfUpgrade: Joi.number().integer().min(0).optional(),
    maxDurationInDays: Joi.number().integer().min(0).optional(),
    maxDurationInYears: Joi.number().integer().min(0).optional(),
    maxPrice: Joi.number().integer().min(0).optional(),
    maxDiscount: Joi.number().integer().min(0).optional(),
    maxNumberOfSubBrands: Joi.number().integer().min(0).optional(),
    maxPaidAmount: Joi.number().integer().min(0).optional(),
    maxDueAmount: Joi.number().integer().min(0).optional(),
    maxNumberOfUpgrade: Joi.number().integer().min(0).optional(),
    startDate: Joi.date().iso().optional(),
    endDate: Joi.date().iso().optional(),
    expiryDate: Joi.date().iso().optional(),
    upgradeDate: Joi.date().iso().optional(),
    minStartDate: Joi.date().iso().optional(),
    minEndDate: Joi.date().iso().optional(),
    minExpiryDate: Joi.date().iso().optional(),
    minUpgradeDate: Joi.date().iso().optional(),
    maxStartDate: Joi.date().iso().optional(),
    maxEndDate: Joi.date().iso().optional(),
    maxExpiryDate: Joi.date().iso().optional(),
    maxUpgradeDate: Joi.date().iso().optional(),
  });
  return schema.validate(payload, {
    abortEarly: false,
    allowUnknown: false,
  });
};
