/**
 * The 32 admin requests that used to live only in the three feature-slice
 * collections.
 *
 * ### ⚠️ Why they moved
 *
 * `trydood-brand-verification`, `trydood-security-changes` and
 * `trydood-subscription` were never admin panels — each was a slice of work
 * that happened to need an admin token. But between them they held the **only**
 * request for 32 admin routes, so deleting them would have taken those
 * endpoints' coverage with them and `verifyApiCoverage` would have gone from
 * green to 32 short in one commit.
 *
 * Lifted from the shipped JSON by script rather than retyped, and diffed field
 * by field against the source, so no description or assertion was reworded on
 * the way in.
 */

const { req, folder } = require("./builders");

const ADM = "admin_token";

// ----------------------------------------------------------------------

const fauthAdminOnlyFlows = folder(
  "16 — Auth (admin-only flows)",
  "Migrate kiye gaye requests — dekho file ke upar wala note.",
  [
    req({
      name: "Register (ab isAdmin ke peeche)",
      method: "POST",
      segments: ["auth", "register"],
      token: ADM,
      body: {"name":"New Admin","email":"newadmin@trydood.com","username":"new_admin","password":"Str0ngPass1","dob":"1990-01-15","mobile":"9800000000","whatsappNumber":"9800000000","role":"ADMIN"},
      description: [
        "### 🔄 Kya badla",
        "",
        "**Pehle public tha aur `role` ka default `ADMIN` tha** — matlab koi bhi khud ko super admin bana sakta tha.",
        "",
        "Ab: `isAdmin` gate, aur `role` **required** hai (koi default nahi).",
        "",
        "---",
        "",
        "`role` values: ADMIN, VENDOR, SUB_VENDOR, CUSTOMER",
        "",
        "⚠️ **Pehla admin API se nahi ban sakta** — bootstrap CLI se hota hai:",
        "",
        "```bash",
        "node scripts/seedAdmin.js \\",
        "  --email admin@trydood.com --password 'Str0ngPass1' \\",
        "  --name \"Admin User\" --username admin_user --mobile 9800000000 --apply",
        "```",
        "",
        "`--apply` ke bina wo dry run hai.",
        "",
        "⚠️ Dobara chalane par `400 \"already exists\"` aata hai, aur wo sahi jawab",
        "hai — email `{email, role}` par unique hai. Seeder is row ko har run se",
        "pehle hataata hai, to pehla run `201` deta hai.",
        "",
        "_(security-changes collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"bana, ya pehle se maujood\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.oneOf([200, 201, 400, 409]);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  if (pm.response.code >= 400) {",
        "    pm.expect(String(b.message)).to.match(/already exists|already registered/i);",
        "  }",
        "});",
        "",
      ],
    }),

    req({
      name: "Set Password (ab isAdmin)",
      method: "POST",
      segments: ["auth", "set-password"],
      token: ADM,
      body: {"currentPassword":"{{admin_password}}","newPassword":"N3wStr0ngPass"},
      description: [
        "### 🔄 Kya badla",
        "",
        "Gate `verifyJwtToken` se **`isAdmin`** ho gaya.",
        "",
        "---",
        "",
        "Pehli baar set kar rahe hain to `currentPassword` **mat bhejein** — `GET /users/get` ka `passwordSetAt` batata hai ki password hai ya nahi.",
        "",
        "Strength: 8–72 chars, kam se kam ek uppercase + ek lowercase + ek number.",
        "",
        "_(security-changes collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"envelope aur ek soch-samajh kar diya gaya status\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.below(500);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
      ],
    }),

    req({
      name: "Reset Password (ADMIN only)",
      method: "POST",
      segments: ["auth", "reset-password"],
      body: {"type":"EMAIL","target":"{{admin_email}}","otp":"{{otp}}","role":"ADMIN","newPassword":"N3wStr0ngPass"},
      description: [
        "### 🔄 Kya badla",
        "",
        "`role` ab **sirf `ADMIN`**.",
        "",
        "---",
        "",
        "OTP `password-reset` purpose pe verify hota hai — login ka OTP yahan replay nahi ho sakta. Success pe code consume ho jaata hai.",
        "",
        "**Token issue nahi hota** — reset karne se session nahi milta, user naye password se login kare.",
        "",
        "⚠️ Iska saved example ek refusal hai. `otp` ek asli inbox se aata hai aur",
        "collection use padh nahi sakti — wahi wajah jo email-verify wale request",
        "ki hai. Success ka shape doc me hai.",
        "",
        "_(security-changes collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"reset hua, ya code ka documented refusal\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.oneOf([200, 401, 403, 422]);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "});",
        "",
      ],
    }),
  ],
);

// ----------------------------------------------------------------------

const fpromoCodes = folder(
  "17 — Promo Codes",
  "Migrate kiye gaye requests — dekho file ke upar wala note.",
  [
    req({
      name: "Create Promo Code",
      method: "POST",
      segments: ["promoCodes", "create"],
      token: ADM,
      body: {"code":"LAUNCH20","audience":"VENDOR","description":"Launch offer - 20% off, capped at Rs1,000","discountType":"PERCENT","discountPercent":20,"maxDiscountAmount":1000,"minOrderValue":1999,"applicableActions":["NEW","UPGRADE"],"firstTimeOnly":false,"validFrom":"2026-08-24","validTill":"2026-12-31","totalUsageLimit":500,"perBrandUsageLimit":1,"isActive":true},
      description: [
        "Admin only. `discountType`: PERCENT | FLAT. `maxDiscountAmount` caps a PERCENT code and is rejected on a FLAT one. `minOrderValue` is checked against the **plan-discounted** subtotal, matching where the promo actually applies. Empty `subscriptionIds` / `applicableActions` mean no restriction.",
        "",
        "**`audience`** decides which checkout the code belongs to — `VENDOR` (subscriptions, the default) or `CUSTOMER` (voucher claims). The two are fully isolated: a CUSTOMER code offered at subscription checkout is reported exactly like a code that does not exist, so the response cannot be used to probe which codes are live.",
        "",
        "Each audience has its own scope fields, and supplying the other side's is a **422** rather than a code that silently never matches:",
        "",
        "| | VENDOR | CUSTOMER |",
        "|---|---|---|",
        "| scope | `subscriptionIds`, `applicableActions` | `voucherIds`, `brandIds`, `categoryIds` |",
        "| minimum | `minOrderValue` (plan-discounted subtotal) | `minBillAmount` (the raw bill the customer typed) |",
        "| per-owner cap | `perBrandUsageLimit` | `perCustomerUsageLimit` |",
        "| first-time | `firstTimeOnly` | `firstOrderOnly` |",
        "| applies to | the plan subtotal | `appliesTo`: NET_BILL or CONVENIENCE_FEE |",
        "",
        "`audience` is **immutable after creation** — the ledger counts redemptions per audience, so flipping it would orphan that history and let a single-use code be redeemed again. See the next request for a CUSTOMER code.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 201\", function () {",
        "    pm.response.to.have.status(201);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"code normalised and stored\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d.code).to.eql(\"LAUNCH20\");",
        "    pm.expect(d.usedCount).to.eql(0);",
        "});",
        "",
        "const b = pm.response.json();",
        "if (b.data && b.data._id) {",
        "    pm.environment.set(\"promo_code_id\", b.data._id);",
        "    pm.environment.set(\"promo_code\", b.data.code);",
        "}",
      ],
    }),

    req({
      name: "List Promo Codes",
      method: "GET",
      segments: ["promoCodes", "get-all"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "20", description: "Max 100" },
        { key: "search", value: "", disabled: true, description: "Matches code or description" },
        { key: "status", value: "LIVE", disabled: true, description: "LIVE | SCHEDULED | EXPIRED — the effective state, which the stored flags alone do not express" },
        { key: "isActive", value: "true", disabled: true, description: "true | false" },
        { key: "audience", value: "VENDOR", disabled: true, description: "VENDOR | CUSTOMER — subscription codes or voucher-claim codes. Omit to list both, which is rarely what a campaign view wants: the two have different economics and different scope fields." },
        { key: "sortBy", value: "createdAt", description: "createdAt | code | usedCount | validTill" },
        { key: "sortOrder", value: "desc", description: "asc | desc" },
      ],
      token: ADM,
      description: [
        "Admin only. `consumedCount` and `reservedCount` come from the **ledger**, not the `usedCount` counter, so you can tell actual redemptions apart from codes sitting in open checkouts. ⚠️ Returns 404 when empty.",
        "",
        "Use **`?audience=`** to separate the two campaign types. Codes created before `audience` existed have no stored value and are treated as `VENDOR` everywhere, including here.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"ledger counts present\", function () {",
        "    const rows = pm.response.json().data.data;",
        "    pm.expect(rows[0]).to.have.property(\"consumedCount\");",
        "    pm.expect(rows[0]).to.have.property(\"reservedCount\");",
        "});",
      ],
    }),

    req({
      name: "Get Promo Code (with ledger)",
      method: "GET",
      segments: ["promoCodes", "get", "{{promo_code_id}}"],
      token: ADM,
      description: [
        "Admin only. Returns the code plus its 50 most recent claims — who redeemed it, on which transaction, for how much. That ledger is what makes a discount auditable; `usedCount` alone cannot answer it.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"ledger returned\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d).to.have.property(\"usage\");",
        "    pm.expect(d.recentUsages).to.be.an(\"array\");",
        "});",
      ],
    }),

    req({
      name: "Update Promo Code",
      method: "PUT",
      segments: ["promoCodes", "update", "{{promo_code_id}}"],
      token: ADM,
      body: {"totalUsageLimit":1000,"validTill":"2027-03-31","isActive":true},
      description: [
        "Admin only. The `code` string itself is **immutable** — it is the identity vendors were given and every ledger row references it. `totalUsageLimit` cannot be lowered below what has already been claimed, which would silently disable the code.",
        "",
        "**`audience` is immutable too**, for the same reason: every `PromoCodeUsage` row froze it at claim time and the per-owner cap is counted by it, so flipping it would orphan that history and let a single-use code be redeemed a second time. Re-sending the value it already has is fine; changing it is a 422. Codes created before the field existed count as `VENDOR`, so they cannot be promoted to `CUSTOMER` either.",
        "",
        "**`costBearing` merges rather than replaces.** Sending `{ \"costBearing\": { \"mode\": \"SHARED\" } }` on a code that already has `vendorPercent: 40` keeps the 40 — a partial patch that silently dropped it would leave a shared-cost code settling nothing to the vendor. Send the field you want to change and only that field changes.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"updated, ledger echoed\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d.promoCode.totalUsageLimit).to.eql(1000);",
        "    pm.expect(d).to.have.property(\"usage\");",
        "});",
      ],
    }),

    req({
      name: "Campaign Report",
      method: "GET",
      segments: ["promoCodes", "reports"],
      query: [
        { key: "code", value: "LAUNCH20", disabled: true, description: "Either this or promoCodeId. Omit both to report on every code" },
        { key: "promoCodeId", value: "{{promo_code_id}}", disabled: true, description: "Alternative to code" },
        { key: "from", value: "2026-08-01", disabled: true, description: "ISO date, inclusive" },
        { key: "to", value: "2026-08-31", disabled: true, description: "ISO date, inclusive of the whole day" },
        { key: "groupBy", value: "day", disabled: true, description: "day | month - buckets for the overTime series" },
        { key: "audience", value: "VENDOR", disabled: true, description: "VENDOR | CUSTOMER — scopes the whole report to one campaign type. Omit to report on both together, which mixes subscription revenue with voucher-claim revenue. When `code` or `promoCodeId` names a single code, that code's own audience is used and contradicting it here is a 422 rather than a page of zeroes." },
      ],
      token: ADM,
      description: [
        "How a campaign actually performed. Every filter is optional; with none it reports on every code over all time, which is the dashboard-landing case.",
        "",
        "**Scope it with `audience`.** Vendor subscription codes and customer voucher codes have different economics, so summing them produces a number that means nothing. It also matters mechanically: `brandId` is not set on a customer claim, so without the filter every customer row collapses into one null bucket in the by-brand sections. Naming a specific `code` takes the audience from the code itself — including codes created before the field existed, which count as `VENDOR`.",
        "",
        "**Reads the ledger, not `usedCount`.** The counter is a fast approximation kept for the cap check. Only `CONSUMED` rows are redemptions — a `RESERVED` row is an open checkout and a `RELEASED` one is abandoned, and counting either as a redemption would overstate every campaign. `campaign.usedCount` is still returned alongside, so drift between the two is visible.",
        "",
        "**Revenue comes from the transaction's frozen `pricing.totalPayable`**, so raising a plan's price next month does not retroactively rewrite what a campaign brought in.",
        "",
        "| Field | Means |",
        "|---|---|",
        "| `claims` | every time the code was taken to checkout |",
        "| `redemptions` | claims that were paid for |",
        "| `openReservations` | checkouts still in flight |",
        "| `abandoned` | checkouts that never paid |",
        "| `conversionRate` | redemptions / claims, as a percentage |",
        "| `discountGiven` | what the campaign cost |",
        "| `revenueBeforePromo` | revenue + discount, so the cost is explicit |",
        "",
        "The window filters on when the claim was **made**, so a checkout started inside it and paid just after still belongs to the campaign that produced it. `byAction` uses the subscription-history row for the same transaction and excludes `ORDER_CREATED`, which every paid transaction also carries.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"only paid claims count as redemptions\", function () {",
        "    const s = pm.response.json().data.summary;",
        "    pm.expect(s.redemptions).to.be.at.most(s.claims);",
        "    pm.expect(s.redemptions + s.openReservations + s.abandoned).to.eql(s.claims);",
        "});",
        "",
        "pm.test(\"breakdowns reconcile with the summary\", function () {",
        "    const d = pm.response.json().data;",
        "    const byPlan = d.byPlan.reduce(function (a, p) { return a + p.revenueCollected; }, 0);",
        "    pm.expect(byPlan).to.be.closeTo(d.summary.revenueCollected, 0.01);",
        "    const byAction = d.byAction.reduce(function (a, x) { return a + x.claims; }, 0);",
        "    pm.expect(byAction, \"a duplicated join would push this over\").to.eql(d.summary.claims);",
        "});",
        "",
        "pm.test(\"the cost of the campaign is stated\", function () {",
        "    const s = pm.response.json().data.summary;",
        "    pm.expect(s.revenueBeforePromo).to.be.closeTo(s.revenueCollected + s.discountGiven, 0.01);",
        "});",
      ],
    }),

    req({
      name: "Delete Promo Code",
      method: "DELETE",
      segments: ["promoCodes", "delete", "{{promo_code_id}}"],
      token: ADM,
      description: [
        "Admin only. **Soft delete** — `PromoCodeUsage` rows reference it and those are the discount ledger. To simply stop a code being accepted, set `isActive: false` instead; this is for removing it from the admin list entirely.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"soft deleted\", function () {",
        "    pm.expect(pm.response.json().data).to.have.property(\"deletedPromoCodeId\");",
        "});",
      ],
    }),
  ],
);

// ----------------------------------------------------------------------

const fsubscribedsGrantCancelForfeit = folder(
  "18 — Subscribeds (grant, cancel, forfeit)",
  "Migrate kiye gaye requests — dekho file ke upar wala note.",
  [
    req({
      name: "List All Subscriptions",
      method: "GET",
      segments: ["subscribeds", "admin", "get-all"],
      query: [
        { key: "page", value: "1", description: "1-based page number" },
        { key: "limit", value: "10", description: "Rows per page, max 100" },
        { key: "search", value: "", disabled: true, description: "Matches brand name, legal name, merchantId, plan name, referenceNumber" },
        { key: "brandId", value: "{{brand_id}}", disabled: true, description: "Filter to one brand" },
        { key: "subscriptionId", value: "{{plan_proplus_id}}", disabled: true, description: "Filter to one plan" },
        { key: "status", value: "ACTIVE", disabled: true, description: "PENDING | ACTIVE | EXPIRED | UPGRADED | DOWNGRADED | CANCELLED" },
        { key: "source", value: "ADMIN_MANUAL", disabled: true, description: "PAYMENT | ADMIN_PAYMENT | ADMIN_MANUAL" },
        { key: "fromDate", value: "2026-08-01", disabled: true, description: "ISO date, filters createdAt" },
        { key: "toDate", value: "2026-08-23", disabled: true, description: "ISO date, filters createdAt" },
        { key: "sortBy", value: "createdAt", description: "createdAt | endDate | startDate | paidAmount" },
        { key: "sortOrder", value: "desc", description: "asc | desc" },
      ],
      token: ADM,
      description: [
        "Admin only. **Read-only, so it deliberately does not self-heal** stale rows — a listing must not write. `isLapsed` is computed in the pipeline instead: `true` means the row still says ACTIVE but its end date has passed, i.e. exactly what the expiry job has yet to sweep.",
        "",
        "⚠️ Returns **404** when empty (shared `pagination` behaviour).",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"rows carry status, plan and brand\", function () {",
        "    const rows = pm.response.json().data.data;",
        "    pm.expect(rows).to.be.an(\"array\").that.is.not.empty;",
        "    pm.expect(rows[0]).to.have.property(\"status\");",
        "    pm.expect(rows[0]).to.have.property(\"plan\");",
        "    pm.expect(rows[0]).to.have.property(\"brand\");",
        "});",
        "",
        "pm.test(\"flags rows the expiry job has not swept yet\", function () {",
        "    const lapsed = (pm.response.json().data.data || []).filter(function (r) { return r.isLapsed; });",
        "    if (lapsed.length) {",
        "        console.warn(lapsed.length + \" row(s) are ACTIVE past their end date — run the expiry job or PUT /subscribeds/admin/resync\");",
        "    }",
        "    pm.expect(true).to.be.true;",
        "});",
      ],
    }),

    req({
      name: "Grant Subscription — FREE (complimentary)",
      method: "POST",
      segments: ["subscribeds", "admin", "grant"],
      token: ADM,
      body: {"brandId":"{{other_brand_id}}","subscriptionId":"{{plan_proplus_id}}","paymentMode":"FREE","note":"Complimentary plan — launch partner"},
      description: [
        "Admin only. No online payment. `note` is **required** — a manual grant must always say why. Gated by `allowAdminFreeGrant`.",
        "",
        "Sets `isFreeGrant: true`, `paidAmount: 0`, and still records the full tax position on the invoice.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 201\", function () {",
        "    pm.response.to.have.status(201);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"granted and live\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d.subscribed.status).to.eql(\"ACTIVE\");",
        "    pm.expect(d.subscribed.source).to.eql(\"ADMIN_MANUAL\");",
        "    pm.expect(d.subscribed.isFreeGrant).to.be.true;",
        "});",
        "",
        "pm.test(\"manual transaction written for reporting\", function () {",
        "    const t = pm.response.json().data.transaction;",
        "    pm.expect(t.gateway).to.eql(\"MANUAL\");",
        "    pm.expect(t.manualPaymentMode).to.eql(\"FREE\");",
        "    pm.expect(t.razorpayOrderId).to.match(/^MANUAL-/);",
        "    pm.expect(t.paidAmount).to.eql(0);",
        "});",
        "",
        "pm.test(\"GST still recorded on a free grant\", function () {",
        "    const p = pm.response.json().data.pricing;",
        "    pm.expect(p.gstAmount).to.be.above(0);",
        "});",
        "",
        "const d = pm.response.json().data;",
        "pm.environment.set(\"subscribed_id\", d.subscribed._id);",
        "pm.environment.set(\"transaction_id\", d.transaction._id);",
      ],
    }),

    req({
      name: "Resync Brand Subscription (repair)",
      method: "PUT",
      segments: ["subscribeds", "admin", "resync"],
      token: ADM,
      body: {"brandId":"{{other_brand_id}}"},
      description: [
        "Admin only. **Purely corrective** — changes no plan, no date and no outlet, so it is safe to run against any brand at any time.",
        "",
        "Recomputes the live plan from the Subscribed docs, re-applies the plan's entitlements, and recounts outlet/franchise usage from the actual SubBrand rows. Use it after: editing data directly in the DB, setting `entitlements` on a plan brands are already on, or a crash between an atomic slot reserve and the SubBrand insert.",
        "",
        "`countersDrifted: true` means the cached counters disagreed with reality and have been corrected.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"before/after reported\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d).to.have.property(\"before\");",
        "    pm.expect(d).to.have.property(\"after\");",
        "});",
        "",
        "pm.test(\"drift surfaced\", function () {",
        "    const d = pm.response.json().data;",
        "    if (d.countersDrifted) {",
        "        console.warn(\"Counters had drifted and were corrected: \" + JSON.stringify(d.before) + \" -> \" + JSON.stringify(d.after));",
        "    }",
        "    pm.expect(d).to.have.property(\"countersDrifted\");",
        "});",
        "",
        "pm.test(\"entitlements now sourced from the plan\", function () {",
        "    const d = pm.response.json().data;",
        "    if (d.entitlementsSource !== \"DB\") {",
        "        console.warn(\"Still \" + d.entitlementsSource + \" — set entitlements on the plan: \" + (d.entitlementWarnings || []).join(\" | \"));",
        "    }",
        "    pm.expect([\"DB\", \"DERIVED\", \"DEFAULT\"]).to.include(d.entitlementsSource);",
        "});",
      ],
    }),

    req({
      name: "Cancel Subscription",
      method: "PUT",
      segments: ["subscribeds", "admin", "cancel"],
      token: ADM,
      body: {"brandId":"{{other_brand_id}}","reason":"Chargeback raised — access revoked pending resolution"},
      description: [
        "Admin only. Ends the plan immediately (`status: CANCELLED`, `endDate: now`) and strips the brand's limits to 0 so nothing new can be created.",
        "",
        "**No existing outlet, franchise, voucher or showcase entry is touched** — revoking a plan is not a data deletion, and everything comes back the moment the brand resubscribes. `reason` is required.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"cancelled immediately\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d.subscribed.status).to.eql(\"CANCELLED\");",
        "    pm.expect(d.isSubscribed).to.be.false;",
        "});",
        "",
        "pm.test(\"limits stripped but usage preserved\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d.limits.subBrands.limit).to.eql(0);",
        "    pm.expect(d.limits.franchises.limit).to.eql(0);",
        "    pm.expect(d.usage).to.have.property(\"subBrandsUsed\");",
        "});",
      ],
    }),

    req({
      name: "List Forfeited Terms (goodwill worklist)",
      method: "GET",
      segments: ["subscribeds", "admin", "forfeited"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "20", description: "Max 100" },
        { key: "compensated", value: "false", disabled: true, description: "false (default view) | true — whether the forfeit has been settled" },
        { key: "minDays", value: "7", disabled: true, description: "Ignore trivial forfeits, e.g. only 7+ days lost" },
        { key: "brandId", value: "{{brand_id}}", disabled: true, description: "Filter to one brand" },
        { key: "fromDate", value: "2026-08-01", disabled: true, description: "ISO date, filters upgradeDate" },
        { key: "toDate", value: "2026-08-24", disabled: true, description: "ISO date, filters upgradeDate" },
        { key: "sortBy", value: "forfeitedValue", description: "forfeitedValue | forfeitedDays | upgradeDate" },
        { key: "sortOrder", value: "desc", description: "asc | desc" },
      ],
      token: ADM,
      description: [
        "Admin only. Vendors who lost paid-for days by changing plan mid-term. `forfeitedValue` is the pro-rata rupee value taken from that plan's **taxable** value, so a compensation decision is not tangled up with GST. ⚠️ Returns 404 when empty.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"forfeit figures present\", function () {",
        "    const rows = pm.response.json().data.data;",
        "    pm.expect(rows[0]).to.have.property(\"forfeitedDays\");",
        "    pm.expect(rows[0]).to.have.property(\"forfeitedValue\");",
        "});",
        "",
        "const rows = pm.response.json().data.data || [];",
        "if (rows.length && rows[0]._id) {",
        "    pm.environment.set(\"forfeited_subscribed_id\", rows[0]._id);",
        "}",
      ],
    }),

    req({
      name: "Mark Forfeit Compensated",
      method: "PUT",
      segments: ["subscribeds", "admin", "forfeited", "compensate"],
      token: ADM,
      body: {"subscribedId":"{{forfeited_subscribed_id}}","note":"6-month extension granted as goodwill - see CRM ticket #5120"},
      description: [
        "Admin only. A **bookkeeping stamp**: it moves no money and changes no plan. If the compensation is a free extension, grant it through `POST /subscribeds/admin/grant` and describe that here. Keeps the forfeited list an actionable worklist rather than a pile that only grows.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"stamped\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d.forfeitCompensatedAt).to.be.a(\"string\");",
        "});",
      ],
    }),
  ],
);

// ----------------------------------------------------------------------

const fplatformSettings = folder(
  "19 — Platform Settings",
  "Migrate kiye gaye requests — dekho file ke upar wala note.",
  [
    req({
      name: "Get Settings",
      method: "GET",
      segments: ["settings", "get"],
      token: ADM,
      description: [
        "Admin only (`isAdmin`). Response carries `vendor.subscription` **and the full `customer` tree**. Upserts the singleton doc with defaults on first read (`helpers/settings/getSetting.js`).",
        "",
        "⚠️ A doc created before a block existed will not have that block stored — a Mongoose default applies on write only. `getCustomerConfig()` falls back to `constants/customer.js` for anything missing, so reads are always complete even when the stored document is not.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"subscription config present\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d.vendor).to.have.property(\"subscription\");",
        "    pm.expect(d.vendor.subscription).to.have.property(\"gstPercentage\");",
        "});",
        "",
        "pm.test(\"companyStateCode is configured (needed for correct CGST/SGST)\", function () {",
        "    const s = pm.response.json().data.vendor.subscription;",
        "    if (!s.companyStateCode) {",
        "        console.warn(\"companyStateCode is blank — all tax will be billed as IGST\");",
        "    }",
        "    pm.expect(s).to.have.property(\"companyStateCode\");",
        "});",
      ],
    }),

    req({
      name: "Update Settings — subscription config",
      method: "PUT",
      segments: ["settings", "update"],
      token: ADM,
      body: {"vendor":{"subscription":{"gstPercentage":18,"isGstInclusive":false,"companyName":"TRYDOOD RETAIL PRIVATE LIMITED","companyGstin":"33AAKCT3750H1ZB","companyAddress":"2nd Floor, Phase-3, Suite No. 250, No. S101, Door No. 769, Spencer Plaza, Anna Salai, Chennai, Tamil Nadu, 600002","companyStateCode":"33","companyState":"Tamil Nadu","hsnSacCode":"998315","allowVendorDowngrade":false,"allowAdminDowngrade":true,"allowAdminFreeGrant":true,"gracePeriodDays":0,"expiryJobIntervalMinutes":60,"isEmailNotificationEnabled":true,"isPushNotificationEnabled":true,"isWhatsAppNotificationEnabled":false}}},
      description: [
        "Admin only. **Merged, not replaced** (`services/settings/updateSetting.js`) — send only the keys you want to change, and anything you omit keeps its current value.",
        "",
        "`companyStateCode` must be a 2-digit GST state code; it decides intra-state CGST+SGST versus inter-state IGST on every invoice.",
        "",
        "**`isPromoCodeEnabled`** gates the whole promo feature and is **true** in this environment. It is left out of the body above on purpose — sending `false` by accident would switch promo codes off platform-wide.",
        "",
        "**Notification channels.** One kill switch each; the in-app row is always written regardless, so these only govern outbound delivery:",
        "",
        "| Flag | Default | Also needs |",
        "|---|---|---|",
        "| `isEmailNotificationEnabled` | `true` | SMTP configured |",
        "| `isPushNotificationEnabled` | `true` | `FCM_PROJECT_ID` / `FCM_CLIENT_EMAIL` / `FCM_PRIVATE_KEY` |",
        "| `isWhatsAppNotificationEnabled` | **`false`** | a `WHATSAPP_TEMPLATE_<TYPE>` env var per message type |",
        "",
        "WhatsApp needs **both** gates: this flag on, *and* an approved template for that specific notification type. Either one missing is a clean skip, not an error — which is what lets templates be switched on one at a time as Meta approves them.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"values applied\", function () {",
        "    const s = pm.response.json().data.vendor.subscription;",
        "    pm.expect(s.gstPercentage).to.eql(18);",
        "    pm.expect(s.companyStateCode).to.eql(\"33\");  // GSTIN 33… = Tamil Nadu",
        "});",
        "",
        "pm.test(\"other blocks untouched by the merge\", function () {",
        "    const v = pm.response.json().data.vendor;",
        "    pm.expect(v).to.have.property(\"voucher\");",
        "    pm.expect(v).to.have.property(\"showcase\");",
        "});",
      ],
    }),
  ],
);

// ----------------------------------------------------------------------

const fwebhooksReplay = folder(
  "20 — Webhooks & Replay",
  "Migrate kiye gaye requests — dekho file ke upar wala note.",
  [
    req({
      name: "List Disputes (chargeback worklist)",
      method: "GET",
      segments: ["transactions", "disputes"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "20", description: "Max 100" },
        { key: "status", value: "OPEN", disabled: true, description: "OPEN | UNDER_REVIEW | ACTION_REQUIRED | WON | LOST | CLOSED" },
        { key: "resolved", value: "false", disabled: true, description: "Omit for unresolved only; true for settled cases" },
        { key: "brandId", value: "{{brand_id}}", disabled: true, description: "Filter to one brand" },
        { key: "sortOrder", value: "asc", description: "asc = soonest deadline first (the order to work in)" },
      ],
      token: ADM,
      description: [
        "Admin only. Sorted by `disputeRespondBy` ascending, because that is the order they must be worked in — **missing the deadline forfeits the money automatically**.",
        "",
        "`daysToRespond` is computed live; `isUrgent` means 2 days or fewer, `isOverdue` means the deadline has already passed. Defaults to unresolved disputes since settled ones need no action.",
        "",
        "⚠️ Returns 404 when there are none — the good outcome.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"deadline fields present\", function () {",
        "    const rows = pm.response.json().data.data;",
        "    pm.expect(rows[0]).to.have.property(\"daysToRespond\");",
        "    pm.expect(rows[0]).to.have.property(\"isOverdue\");",
        "});",
        "",
        "const rows = pm.response.json().data.data || [];",
        "const urgent = rows.filter(function (d) { return d.isUrgent || d.isOverdue; });",
        "if (urgent.length) {",
        "    console.warn(urgent.length + \" dispute(s) are urgent or overdue — submit evidence now.\");",
        "}",
      ],
    }),

    req({
      name: "List Webhook Events (failed by default)",
      method: "GET",
      segments: ["transactions", "webhook", "events"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "20", description: "Max 100" },
        { key: "status", value: "FAILED", disabled: true, description: "Omit for FAILED (the actionable set). RECEIVED | PROCESSED | IGNORED | DUPLICATE | FAILED | ALL" },
        { key: "event", value: "payment.captured", disabled: true, description: "payment.captured | order.paid | payment.failed | refund.processed | payment.dispute.*" },
        { key: "transactionId", value: "{{transaction_id}}", disabled: true, description: "Filter to one transaction" },
        { key: "brandId", value: "{{brand_id}}", disabled: true, description: "Filter to one brand" },
        { key: "razorpayOrderId", value: "{{razorpay_order_id}}", disabled: true, description: "Filter to one order" },
        { key: "fromDate", value: "2026-08-01", disabled: true, description: "ISO date" },
        { key: "toDate", value: "2026-08-24", disabled: true, description: "ISO date" },
        { key: "sortOrder", value: "desc", description: "asc | desc" },
      ],
      token: ADM,
      description: [
        "Admin only. Defaults to `status: FAILED`. **`needsAttention: true` is the one to act on** — a failed delivery whose transaction is still unverified, i.e. money in and nothing granted; those sort to the top regardless of date. `needsAttentionTotal` counts them across the whole collection so the panel can badge it.",
        "",
        "The raw `payload` is excluded here to keep the list readable — fetch a single event to see it.",
        "",
        "⚠️ Returns **404** when nothing matches, which on this endpoint is the *good* outcome: no failed deliveries.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"attention flags present\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d).to.have.property(\"needsAttentionTotal\");",
        "    pm.expect(d.data[0]).to.have.property(\"needsAttention\");",
        "    pm.expect(d.data[0]).to.have.property(\"isReplayable\");",
        "});",
        "",
        "const d = pm.response.json().data;",
        "if (d.needsAttentionTotal > 0) {",
        "    console.warn(d.needsAttentionTotal + \" delivery(s) captured money without activating a plan — replay them.\");",
        "}",
        "const first = (d.data || [])[0];",
        "if (first && first.eventId) {",
        "    pm.environment.set(\"webhook_event_id\", first.eventId);",
        "}",
      ],
    }),

    req({
      name: "Get Webhook Event (with raw payload)",
      method: "GET",
      segments: ["transactions", "webhook", "events", "{{webhook_event_id}}"],
      token: ADM,
      description: [
        "Admin only. Accepts either Razorpay's event id or our own document id, since the listing gives you the latter. Includes the **raw payload** — inspect it before replaying, especially if the failure was a data problem rather than an outage.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"raw payload available for inspection\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d).to.have.property(\"payload\");",
        "    pm.expect(d).to.have.property(\"isReplayable\");",
        "});",
      ],
    }),

    req({
      name: "Replay Webhook Event",
      method: "POST",
      segments: ["transactions", "webhook", "replay", "{{webhook_event_id}}"],
      token: ADM,
      body: {"force":false},
      description: [
        "Admin only. Re-runs the stored payload through the **same** processing the receiver uses — the signature is not re-checked, and does not need to be: it was verified when the delivery was stored, the payload has been immutable since, and the caller here is an authenticated admin.",
        "",
        "**Safe to run twice.** The settlement underneath claims the transaction with a conditional update on `verified: false`, so replaying something already settled reports that instead of activating a second subscription.",
        "",
        "Only FAILED and IGNORED events replay by default; re-running a PROCESSED one needs `force: true`. Unlike the receiving endpoint, a replay **reports** its failure rather than swallowing it — the admin is standing right there.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"before/after reported\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d).to.have.property(\"before\");",
        "    pm.expect(d).to.have.property(\"after\");",
        "    pm.expect(d).to.have.property(\"recovered\");",
        "});",
        "",
        "const d = pm.response.json().data;",
        "if (d.recovered) {",
        "    console.log(\"Recovered: \" + d.before.status + \" -> \" + d.after.status);",
        "} else {",
        "    console.warn(\"Not recovered — \" + d.after.outcome);",
        "}",
      ],
    }),

    req({
      name: "payment.captured — activates the subscription",
      method: "POST",
      segments: ["transactions", "webhook", "razorpay"],
      body: {"entity":"event","event":"payment.captured","created_at":1756900000,"payload":{"payment":{"entity":{"id":"pay_QxYz987ZyXwVu6","entity":"payment","amount":589882,"currency":"INR","status":"captured","captured":true,"order_id":"{{razorpay_order_id}}","method":"upi","vpa":"devashish@okhdfcbank","fee":1392,"tax":212}}}},
      description: [
        "Public. `amount` is compared against the paise figure frozen on the transaction, so a short payment cannot activate a plan — the delivery is stored with the mismatch as its error and the transaction stays unverified. Set `razorpay_order_id` to a real pending order first (Create Subscribe Order sets it).",
        "",
        "⚠️ **Iska saved example ek `400` hai, aur wo jaan-boojh kar hai.**",
        "",
        "Signature raw body par banti hai, aur uske liye webhook secret chahiye —",
        "jo ek committed env file me daalna matlab repo me credential rakhna, sirf",
        "ek green tick ke liye. Locally chalane ke liye `x-razorpay-signature`",
        "header me apne secret se banaya HMAC-SHA256 daaliye.",
        "",
        "Refusal khud batane layak hai: endpoint **public** hai aur rate limiter se",
        "bhi chhoot hai (webhook ko `429` dena matlab paisa chup-chaap ruk jaana),",
        "to signature hi uske aage khada ekmatra pehra hai.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"200, ya signature ka documented refusal\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.oneOf([200, 400]);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  if (pm.response.code === 400) {",
        "    pm.expect(String(b.message)).to.include(\"signature\");",
        "  }",
        "});",
        "",
      ],
    }),

    req({
      name: "CUSTOMER account — voucher claim payment",
      method: "POST",
      segments: ["transactions", "webhook", "razorpay", "customer"],
      body: {"entity":"event","event":"payment.captured","created_at":1756900000,"payload":{"payment":{"entity":{"id":"pay_CustVoucher001","order_id":"order_CustVoucher001","status":"captured","captured":true,"amount":76000,"method":"upi","fee":0,"tax":0}}}},
      description: [
        "The **CUSTOMER** Razorpay account's endpoint — voucher claim payments.",
        "",
        "Before this existed, a customer payment hit the vendor endpoint, was looked up without an account scope, and ran straight into `settleSubscriptionPayment` — failing on *\"Subscription plan not found\"*, recording the delivery FAILED and paging admins CRITICAL. On **every** payment.",
        "",
        "Now the account comes from the route, the transaction lookup is scoped to it, and the settler is chosen from `transaction.purpose`. An unknown purpose is a **hard stop with an admin alert**, never a guess — running the wrong settler on a money row is not recoverable the way a FAILED delivery is.",
        "",
        "Until Phase 1B lands there is no `VOUCHER_CLAIM` settler, so a voucher transaction returns the hard-stop outcome below. No such transaction can exist yet either, so in practice this returns `IGNORED`.",
        "",
        "⚠️ **Iska saved example ek `400` hai, aur wo jaan-boojh kar hai.**",
        "",
        "Signature raw body par banti hai, aur uske liye webhook secret chahiye —",
        "jo ek committed env file me daalna matlab repo me credential rakhna, sirf",
        "ek green tick ke liye. Locally chalane ke liye `x-razorpay-signature`",
        "header me apne secret se banaya HMAC-SHA256 daaliye.",
        "",
        "Refusal khud batane layak hai: endpoint **public** hai aur rate limiter se",
        "bhi chhoot hai (webhook ko `429` dena matlab paisa chup-chaap ruk jaana),",
        "to signature hi uske aage khada ekmatra pehra hai.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"200, ya signature ka documented refusal\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.oneOf([200, 400]);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  if (pm.response.code === 400) {",
        "    pm.expect(String(b.message)).to.include(\"signature\");",
        "  }",
        "});",
        "",
      ],
    }),
  ],
);

// ----------------------------------------------------------------------

const fcurationVerificationQueues = folder(
  "21 — Curation & Verification queues",
  "Migrate kiye gaye requests — dekho file ke upar wala note.",
  [
    req({
      name: "List Brand Verifications (queue)",
      method: "GET",
      segments: ["brands", "admin", "verifications"],
      query: [
        { key: "page", value: "1", description: "Number ≥ 1. Default 1." },
        { key: "limit", value: "10", description: "Number 1-100. Default 10." },
        { key: "search", value: "", disabled: true, description: "Regex across brand.brandName, brand.legalBusinessName, brand.uniqueId, brand.merchantId and remarks." },
        { key: "brandId", value: "{{brand_id}}", disabled: true, description: "ObjectId. Narrow to one brand." },
        { key: "status", value: "MANUAL_REVIEW", description: "One of PENDING, APPROVED, MANUAL_REVIEW, UNDER_REVIEW, REJECTED, REVOKED. Lowercase is accepted and upper-cased." },
        { key: "isReviewed", value: "false", description: "Boolean or the strings \"true\"/\"false\"." },
        { key: "isRejected", value: "false", disabled: true, description: "Boolean or string." },
        { key: "isRevoked", value: "false", disabled: true, description: "Boolean or string." },
        { key: "isAdminApproved", value: "false", disabled: true, description: "Boolean or string." },
        { key: "isSuperseded", value: "false", disabled: true, description: "Defaults to false — only live attempts. Send true to include retired attempts." },
        { key: "attemptNumber", value: "1", disabled: true, description: "Number ≥ 1." },
        { key: "reviewedByAdminId", value: "{{admin_user_id}}", disabled: true, description: "ObjectId of the admin who reviewed it." },
        { key: "minScore", value: "75", disabled: true, description: "Number." },
        { key: "maxScore", value: "89", disabled: true, description: "Number." },
        { key: "fromDate", value: "2026-08-01", disabled: true, description: "ISO date." },
        { key: "toDate", value: "2026-08-23", disabled: true, description: "ISO date. Cannot be earlier than fromDate. Inclusive to end-of-day." },
        { key: "sortBy", value: "SCORE", description: "One of NEWEST, OLDEST, SCORE. Default NEWEST." },
        { key: "sortOrder", value: "DESC", description: "One of ASC, DESC. Default DESC. Only affects sortBy=SCORE." },
      ],
      token: ADM,
      description: [
        "**Role:** ADMIN only (`isAdmin`).",
        "",
        "The admin work-queue. Defaults to **live attempts only** (`isSuperseded=false`), so the list is exactly what is actionable.",
        "",
        "Each row carries the full SystemVerify record plus the joined `brand`, `vendor`, and whichever admins acted (`reviewedByAdmin`, `verifiedByAdmin`, `rejectedByAdmin`, `revokedByAdmin`), and three derived counters: `rejectionCount`, `revocationCount`, `submissionCount`.",
        "",
        "⚠️ **Empty result is `404`, not an empty array** — the shared `pagination` utility throws. Render an empty state, not an error toast.",
        "",
        "The `remarks` array is the point of this endpoint: it tells the admin what mismatched, so every document does not have to be opened by hand.",
        "",
        "_(brand-verification collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"response time is acceptable\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"body is JSON with a success flag\", function () {",
        "    const body = pm.response.json();",
        "    pm.expect(body).to.have.property(\"success\");",
        "});",
        "",
        "pm.test(\"queue returns a paginated envelope\", function () {",
        "    pm.response.to.have.status(200);",
        "    const data = pm.response.json().data;",
        "    pm.expect(data).to.have.property(\"total\");",
        "    pm.expect(data).to.have.property(\"totalPages\");",
        "    pm.expect(data.data).to.be.an(\"array\");",
        "});",
        "",
        "const rows = pm.response.json().data.data;",
        "if (rows && rows.length) {",
        "    pm.environment.set(\"brand_id\", rows[0].brandId);",
        "    pm.environment.set(\"system_verify_id\", rows[0]._id);",
        "    console.log(\"brand_id + system_verify_id captured from first row\");",
        "}",
      ],
    }),

    req({
      name: "Admin — top brands list",
      method: "GET",
      segments: ["brands", "admin", "top-brands"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "10" },
      ],
      token: ADM,
      description: [
        "### 🔄 Kya badla",
        "",
        "Naya endpoint.",
        "",
        "---",
        "",
        "Suggested-vouchers list ka mirror. Isme **deactivated brands bhi** aate hain (`isActive: false`) — customer tab unhe chhupa deta hai, par admin ko unhe unpin karne ke liye dikhna zaruri hai.",
        "",
        "_(security-changes collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"envelope aur ek soch-samajh kar diya gaya status\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.below(500);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
      ],
    }),

    req({
      name: "Admin — brand ko top brands me daalo",
      method: "PUT",
      segments: ["brands", "admin", "top-brands", "{{brand_id}}"],
      token: ADM,
      body: {"isTopBrand":true,"topOrder":1},
      description: [
        "### 🔄 Kya badla",
        "",
        "Naya endpoint.",
        "",
        "---",
        "",
        "**Ek hi endpoint add aur remove dono karta hai** — flag `false` bhejna hi remove hai (jaise `subBrands/update` me `isActive`). Already pinned entry pe naya order bhejna reorder hai.",
        "",
        "Stamp (`…At` / `…By`) sirf **pehli** baar pin karne pe likha jaata hai — reorder karne se ye nahi badalta, to record rehta hai ki pehle kisne chuna tha.",
        "",
        "**Body:**",
        "",
        "| Field | Type | Required | Notes |",
        "|---|---|---|---|",
        "| `isTopBrand` | boolean | ✅ | `false` = remove |",
        "| `topOrder` | number | ❌ | Integer ≥ 0. Chhota pehle |",
        "",
        "Deactivated brand bhi pin ho sakta hai — wo customer tab me nahi dikhega, par admin ke view me rahega.",
        "",
        "_(security-changes collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"envelope aur ek soch-samajh kar diya gaya status\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.below(500);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
      ],
    }),

    req({
      name: "Admin — suggested vouchers list",
      method: "GET",
      segments: ["vouchers", "admin", "suggestions"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "10" },
      ],
      token: ADM,
      description: [
        "### 🔄 Kya badla",
        "",
        "Naya endpoint.",
        "",
        "---",
        "",
        "**Ye customer wali list nahi hai.** Customer pipeline expire/unpublished vouchers chhupa deti hai — jo app ke liye sahi hai, par admin screen pe wo pin gayab ho jaata jise wo hataana chahta hai.",
        "",
        "Isliye yahan **sab** pinned vouchers aate hain. Har row pe `status` batata hai kaunsa abhi live hai.",
        "",
        "`banner` object flatten hoke `bannerType` + `bannerUrl` ban jaata hai — wahi shape jo customer list me hai.",
        "",
        "_(security-changes collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"envelope aur ek soch-samajh kar diya gaya status\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.below(500);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
      ],
    }),

    req({
      name: "Admin — voucher ko suggestions me daalo",
      method: "PUT",
      segments: ["vouchers", "admin", "suggestions", "{{voucher_id}}"],
      token: ADM,
      body: {"isSuggested":true,"suggestionOrder":1},
      description: [
        "### 🔄 Kya badla",
        "",
        "Naya endpoint.",
        "",
        "---",
        "",
        "**Ek hi endpoint add aur remove dono karta hai** — flag `false` bhejna hi remove hai (jaise `subBrands/update` me `isActive`). Already pinned entry pe naya order bhejna reorder hai.",
        "",
        "Stamp (`…At` / `…By`) sirf **pehli** baar pin karne pe likha jaata hai — reorder karne se ye nahi badalta, to record rehta hai ki pehle kisne chuna tha.",
        "",
        "**Body:**",
        "",
        "| Field | Type | Required | Notes |",
        "|---|---|---|---|",
        "| `isSuggested` | boolean | ✅ | `false` = remove |",
        "| `suggestionOrder` | number | ❌ | Integer ≥ 0. Chhota pehle. Sirf pin karte waqt matlab rakhta hai |",
        "",
        "_(security-changes collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"envelope aur ek soch-samajh kar diya gaya status\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.below(500);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
      ],
    }),
  ],
);

// ----------------------------------------------------------------------
// Requests that join folders the generator already builds.

const extras = {
  banners: [
    req({
      name: "Banners — create (isAdmin)",
      method: "POST",
      segments: ["banners", "create"],
      token: ADM,
      description: [
        "### 🔄 Kya badla",
        "",
        "`verifyJwtToken` → **`isAdmin`**. Pehle customer bhi app ka home banner bana sakta tha.",
        "",
        "---",
        "",
        "Multipart request — `type` ke hisaab se file field:",
        "`IMAGE` → `image` · `VIDEO` → `video` · `GIF` → `gif`",
        "",
        "Text fields: `title`, `description`, `type`, `redirect[type]`, `redirect[targetId]`, `redirect[url]`, `startDate`, `endDate`, `isActive`",
        "",
        "_(security-changes collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"envelope aur ek soch-samajh kar diya gaya status\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.below(500);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
      ],
    }),
  ],
  legal: [
    req({
      name: "Update Terms & Conditions",
      method: "PUT",
      segments: ["terms-and-conditions", "update", "{{legal_id}}"],
      token: ADM,
      body: {"isActive":false},
      description: [
        "### 🔄 Kya badla",
        "",
        "Do bugs theek hue:",
        "",
        "- **`isActive` toggle karta tha** — `isActive: true` bhejne pe already-active document **band** ho jaata tha (`result.isActive = !result.isActive`)",
        "- **Title change pe crash** — `result.findOne(...)` document pe call ho raha tha, model pe nahi → `result.findOne is not a function`",
        "",
        "Plus `type` ab updatable hai, aur `description` lowercase nahi hota.",
        "",
        "---",
        "",
        "Kam se kam ek field bhejna zaruri hai.",
        "",
        "_(security-changes collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"envelope aur ek soch-samajh kar diya gaya status\", function () {",
        "  pm.expect(pm.response.code, \"status\").to.be.below(500);",
        "  const b = pm.response.json();",
        "  pm.expect(b, \"success flag\").to.have.property(\"success\");",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
      ],
    }),
  ],
  plans: [
    req({
      name: "Update Plan — set entitlements on an existing plan",
      method: "PUT",
      segments: ["subscriptions", "update", "{{subscription_id}}"],
      token: ADM,
      body: {"entitlements":{"subBrands":{"isUnlimited":true},"franchises":{"limit":50,"isUnlimited":false},"vouchers":{"isEnabled":true},"dealPack":{"isEnabled":true},"prioritySupport":{"isEnabled":true},"showcase":{"isEnabled":true}}},
      description: [
        "Admin only. **This is the fix for the DERIVED plans.** Run it once per live plan so `entitlementsSource` becomes `DB` and franchise limits stop resolving to 0. Existing brands then need `PUT /subscribeds/admin/resync` to pick up the new limits.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"franchise limit now explicit\", function () {",
        "    const e = pm.response.json().data.entitlements;",
        "    pm.expect(e.franchises.limit).to.eql(50);",
        "    pm.expect(e.franchises.isUnlimited).to.be.false;",
        "});",
      ],
    }),
  ],
  notifications: [
    req({
      name: "Broadcast - dry run (resolve the audience, send nothing)",
      method: "POST",
      segments: ["notifications", "broadcast"],
      token: ADM,
      body: {"title":"Scheduled maintenance tonight","body":"The dashboard will be briefly unavailable between 2am and 3am IST.","target":{"roles":["VENDOR"]},"severity":"WARNING","dryRun":true},
      description: [
        "**Run this before any wide broadcast.** It resolves the audience and reports its size and role breakdown without writing a single row. 'All customers' is not a number you want to discover after the fact.",
        "",
        "The returned `broadcastId` can be passed straight back into the real send, which makes the pair a two-step confirm.",
        "",
        "_(subscription collection se migrate kiya gaya)_",
      ].join("\n"),
      assert: [
        "pm.test(\"status is 200\", function () {",
        "    pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"responds under 5s\", function () {",
        "    pm.expect(pm.response.responseTime).to.be.below(15000);",
        "});",
        "",
        "pm.test(\"envelope shape\", function () {",
        "    const b = pm.response.json();",
        "    pm.expect(b).to.have.property(\"success\", true);",
        "    pm.expect(b).to.have.property(\"message\");",
        "    pm.expect(b).to.have.property(\"data\");",
        "});",
        "",
        "pm.test(\"nothing was sent\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d.dryRun).to.eql(true);",
        "    pm.expect(d.sent).to.eql(false);",
        "});",
        "",
        "pm.test(\"audience is broken down by role\", function () {",
        "    const d = pm.response.json().data;",
        "    pm.expect(d.recipients).to.be.a(\"number\");",
        "    pm.expect(d).to.have.property(\"byRole\");",
        "    pm.environment.set(\"broadcast_id\", d.broadcastId);",
        "});",
      ],
    }),
  ],
};

module.exports = { fauthAdminOnlyFlows, fpromoCodes, fsubscribedsGrantCancelForfeit, fplatformSettings, fwebhooksReplay, fcurationVerificationQueues, extras };
