/**
 * The vendor side of the money: claims read-only, refunds decided, payouts read.
 *
 * ### ⚠️ Why this file exists
 *
 * These three folders shipped inside `trydood-vendor.postman_collection.json`
 * and **nowhere else**. `generate-vendor-collection.js` built folders 00-18 and
 * knew nothing about them, so the documented regenerate-and-recapture cycle —
 * the one `postman/README.md` tells you to run — deleted 17 requests and 3
 * folders and reported success.
 *
 * That is the same failure the README already records for captured examples,
 * one level up: there, a regenerate lost the *responses*; here it lost the
 * *requests*. Moving them into the generator is what makes the documented
 * workflow safe to follow.
 *
 * Lifted from the shipped JSON rather than retyped, so no description or
 * assertion was reworded on the way in.
 */

const { req, folder } = require("./builders");

const VEN = "vendor_token";

// ----------------------------------------------------------------------

const claimsFolder = folder(
  "18 — Voucher Claims (read-only)",
  [
    "Grahak ne mere outlet par kya khareeda, aur mujhe kitna milega.",
    "",
    "**Phase 1 me poori tarah read-only.** Capture par claim seedhe `REDEEMED` ho jaati hai —",
    "payment hi redemption hai. Outlet scan aur reversal Phase 2 hain",
    "(`docs/customer_voucher_claim_plan.md` §15.1).",
  ].join("\n"),
  [
    req({
      name: "Mere brand ki claims ⭐",
      method: "GET",
      segments: ["voucher-claims"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "20" },
        { key: "status", value: "REDEEMED", disabled: true },
        { key: "outletId", value: "{{sub_brand_id}}", disabled: true },
        { key: "from", value: "2026-08-01", disabled: true },
        { key: "to", value: "2026-08-31", disabled: true },
      ],
      token: VEN,
      description: [
        "customer apne, vendor apne brand ke, sub-vendor apne outlet ke, admin sab dekhta hai.",
        "",
        "| Field | Customer | Vendor / Outlet | Admin |",
        "|---|:-:|:-:|:-:|",
        "| `voucher.convenienceFee` | ✅ | — | ✅ |",
        "| `voucher.vendorPayable` | — | ✅ | ✅ |",
        "| `gatewayFee` · `netReceived` | — | — | ✅ |",
        "| `voucher.platformPromoCost` | — | — | ✅ |",
        "| `email` · `contact` · `customerId` | ✅ (apna) | — | ✅ |",
        "| `invoiceDownloadUrl` | ✅ | — | ✅ |",
        "",
        "> Vendor ko `gatewayFee` / `platformPromoCost` **kabhi nahi** — wo hamara margin hai,",
        "> aur `email` / `contact` customer ki privacy. Dono ek hi document par hain, isiliye",
        "> ye faisla `claimProjection()` me ek jagah hota hai, har call site par yaad nahi rakha jaata.",
        "",
        "`SUB_VENDOR` token isi URL par **sirf apne outlet** ki rows paata hai — brand ki poori nahi.",
        "",
        "⚠️ **Scope query se chaudi nahi ho sakti.** `?brandId=<dusra brand>` bhejne par **kuch nahi**",
        "milta, apne rows nahi — filter aur scope intersect hote hain.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "  pm.expect(b, \"data key\").to.have.property(\"data\");",
        "});",
      ],
    }),

    req({
      name: "Mere brand ke payments",
      method: "GET",
      segments: ["voucher-claims", "payments"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "20" },
        { key: "outletId", value: "{{sub_brand_id}}", disabled: true },
      ],
      token: VEN,
      description: [
        "customer apne, vendor apne brand ke, sub-vendor apne outlet ke, admin sab dekhta hai.",
        "",
        "| Field | Customer | Vendor / Outlet | Admin |",
        "|---|:-:|:-:|:-:|",
        "| `voucher.convenienceFee` | ✅ | — | ✅ |",
        "| `voucher.vendorPayable` | — | ✅ | ✅ |",
        "| `gatewayFee` · `netReceived` | — | — | ✅ |",
        "| `voucher.platformPromoCost` | — | — | ✅ |",
        "| `email` · `contact` · `customerId` | ✅ (apna) | — | ✅ |",
        "| `invoiceDownloadUrl` | ✅ | — | ✅ |",
        "",
        "> Vendor ko `gatewayFee` / `platformPromoCost` **kabhi nahi** — wo hamara margin hai,",
        "> aur `email` / `contact` customer ki privacy. Dono ek hi document par hain, isiliye",
        "> ye faisla `claimProjection()` me ek jagah hota hai, har call site par yaad nahi rakha jaata.",
        "",
        "Vendor ko `voucher.vendorPayable` dikhta hai — jo unhe milega. `gatewayFee`, `netReceived`",
        "aur `voucher.platformPromoCost` **kabhi nahi**: Razorpay ne humse kya liya ye commercial",
        "disclosure hai. `email` / `contact` bhi nahi — wo privacy hai.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "  pm.expect(b, \"data key\").to.have.property(\"data\");",
        "});",
      ],
    }),

    req({
      name: "Ek payment kholo",
      method: "GET",
      segments: ["voucher-claims", "payments", "{{claim_transaction_id}}"],
      token: VEN,
      description: [
        "customer apne, vendor apne brand ke, sub-vendor apne outlet ke, admin sab dekhta hai.",
        "",
        "| Field | Customer | Vendor / Outlet | Admin |",
        "|---|:-:|:-:|:-:|",
        "| `voucher.convenienceFee` | ✅ | — | ✅ |",
        "| `voucher.vendorPayable` | — | ✅ | ✅ |",
        "| `gatewayFee` · `netReceived` | — | — | ✅ |",
        "| `voucher.platformPromoCost` | — | — | ✅ |",
        "| `email` · `contact` · `customerId` | ✅ (apna) | — | ✅ |",
        "| `invoiceDownloadUrl` | ✅ | — | ✅ |",
        "",
        "> Vendor ko `gatewayFee` / `platformPromoCost` **kabhi nahi** — wo hamara margin hai,",
        "> aur `email` / `contact` customer ki privacy. Dono ek hi document par hain, isiliye",
        "> ye faisla `claimProjection()` me ek jagah hota hai, har call site par yaad nahi rakha jaata.",
        "",
        "Vendor ko `payment.invoiceDownloadUrl` **nahi** milta — customer ka tax invoice customer",
        "ke apne details rakhta hai.",
        "",
        "**Errors:** `403` dusre brand ka payment · `403` \"not taken at your outlet\" (sub-vendor) · `404` id galat",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "  pm.expect(b, \"data key\").to.have.property(\"data\");",
        "});",
      ],
    }),

    req({
      name: "Claim code se verify karo (counter par) ⭐",
      method: "GET",
      segments: ["voucher-claims", "code", "{{claim_code}}"],
      token: VEN,
      description: [
        "**Phase 1 me ye read-only hai.** Capture par claim seedhe `REDEEMED` ho jaati hai",
        "(`redemptionMode: AUTO`) — payment hi redemption hai. Ye page batata hai *kitna pay hua,*",
        "*kaunsa offer, kab, kaunsa outlet*.",
        "",
        "> **Phase 2** me asli redemption aayegi (`POST /voucher-claims/redeem`), aur uske saath",
        "> dobara-scan ka samajhdaar jawab aur reversal — teeno ek saath. Sirf scan deploy karna",
        "> grahak ko phansa deta hai: scan chala nahi, saamaan mila nahi, aur *\"already redeemed\"*.",
        "> Dekhein `docs/customer_voucher_claim_plan.md` §15.1.",
        "",
        "⚠️ Code lookup narrow karta hai, **authorise nahi karta** — dusre brand ya dusre outlet ka",
        "code 403 deta hai.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "  pm.expect(b, \"data key\").to.have.property(\"data\");",
        "});",
      ],
    }),

    req({
      name: "Ek claim kholo — timeline ke saath",
      method: "GET",
      segments: ["voucher-claims", "{{claim_id}}"],
      token: VEN,
      description: [
        "customer apne, vendor apne brand ke, sub-vendor apne outlet ke, admin sab dekhta hai.",
        "",
        "| Field | Customer | Vendor / Outlet | Admin |",
        "|---|:-:|:-:|:-:|",
        "| `voucher.convenienceFee` | ✅ | — | ✅ |",
        "| `voucher.vendorPayable` | — | ✅ | ✅ |",
        "| `gatewayFee` · `netReceived` | — | — | ✅ |",
        "| `voucher.platformPromoCost` | — | — | ✅ |",
        "| `email` · `contact` · `customerId` | ✅ (apna) | — | ✅ |",
        "| `invoiceDownloadUrl` | ✅ | — | ✅ |",
        "",
        "> Vendor ko `gatewayFee` / `platformPromoCost` **kabhi nahi** — wo hamara margin hai,",
        "> aur `email` / `contact` customer ki privacy. Dono ek hi document par hain, isiliye",
        "> ye faisla `claimProjection()` me ek jagah hota hai, har call site par yaad nahi rakha jaata.",
        "",
        "`timeline` har audience ke liye **banayi** jaati hai, chhaani nahi — kaccha audit row",
        "`snapshot` me poora pricing block rakhta hai (`platformPromoCost` samet), aur `reason`",
        "staff ka note hai. Vendor ko dono me se kuch nahi.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "  pm.expect(b, \"data key\").to.have.property(\"data\");",
        "});",
      ],
    }),

    req({
      name: "Dusre brand ki claim — 403",
      method: "GET",
      segments: ["voucher-claims", "{{other_brand_claim_id}}"],
      token: VEN,
      description: "Brand-side access parent `brandId` se hota hai; dusre brand ka row 403.",
      assert: [
        "// Dusre brand ka row.",
        "pm.test(\"HTTP 403\", function () {",
        "  pm.response.to.have.status(403);",
        "});",
        "",
        "pm.test(\"failure envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(false);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
      ],
    }),

    req({
      name: "Subscription payment ko claim detail se kholna — 404",
      method: "GET",
      segments: ["voucher-claims", "payments", "{{subscription_transaction_id}}"],
      token: VEN,
      description: [
        "⚠️ Ek hi collection vendor subscriptions aur customer voucher claims dono rakhti hai.",
        "`purpose` scope ke bina ye endpoint apne hi billing row ko — dusre Razorpay account ka,",
        "aur aisi projection se jo voucher claim ke liye bani hai — khol deta. **Id ka unique hona",
        "iska jawab nahi hai.**",
      ].join("\n"),
      assert: [
        "// Ek collection, do money flows — purpose scope isse rokta hai.",
        "pm.test(\"HTTP 404\", function () {",
        "  pm.response.to.have.status(404);",
        "});",
        "",
        "pm.test(\"failure envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(false);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
      ],
    }),
  ],
);

// ----------------------------------------------------------------------

const refundsFolder = folder(
  "19 — Refunds",
  [
    "**Aap tay karte hain, Trydood sirf nikaalta hai.**",
    "",
    "Aapke paas `refund.vendorApprovalHours` (24) ki window hai. Beet gayi to request",
    "aapki rehti hi nahi — Trydood ke paas chali jaati hai. Do reminder pehle aate hain,",
    "taaki timeout kabhi achanak na ho.",
  ].join("\n"),
  [
    req({
      name: "Refund worklist ⭐",
      method: "GET",
      segments: ["refunds"],
      query: [
        { key: "open", value: "true" },
        { key: "page", value: "1" },
        { key: "limit", value: "20" },
        { key: "outletId", value: "{{sub_brand_id}}", disabled: true },
      ],
      token: VEN,
      description: [
        "par **sirf apne outlet** ki rows paata hai.",
        "",
        "`?open=true` par **sabse purani upar** — wahi timeout ke sabse kareeb hai aur usi",
        "grahak ne sabse lamba intezaar kiya. Bina uske sabse nayi upar (history browse karne",
        "ke liye).",
        "",
        "| Field | Customer | Vendor / Outlet | Admin |",
        "|---|:-:|:-:|:-:|",
        "| `split.totalRefund` | ✅ | — | ✅ |",
        "| `split.vendorClawback` · `vendorPromoReversal` | — | ✅ | ✅ |",
        "| `split.platformPromoReversal` · `gatewayFeeAbsorbed` | — | — | ✅ |",
        "| `utr` | ✅ | — | ✅ |",
        "| `vendorNote` | ❌ | apna | ✅ |",
        "| `adminNote` · `overrideReason` | ❌ | ❌ | ✅ |",
        "| `customerId` | ✅ (apna) | ❌ | ✅ |",
        "",
        "> ⚠️ `split` me hamara promo hissa aur wo MDR jo hum khaate hain **usi**",
        "> sub-document par hain jis par `vendorClawback` hai — jo vendor ko sach me",
        "> chahiye. Isiliye ye faisla `refundProjection()` me ek jagah hota hai, har call",
        "> site par yaad nahi rakha jaata.",
        "",
        "`canDecide` response me bataya jaata hai.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
      ],
    }),

    req({
      name: "Refund approve karo ⭐",
      method: "PATCH",
      segments: ["refunds", "{{refund_request_id}}", "approve"],
      token: VEN,
      body: {"approvedAmount":400,"note":"Only the starter was wrong."},
      description: [
        "### ⚠️ Rakam **ghat** sakti hai, **badh nahi**",
        "",
        "*\"Aadha order theek tha, starter nahi\"* asli jawab hai, aur rakam kam karna use dene",
        "ka tareeka hai. Badhana grahak ne jo maanga uski approval nahi — wo naya faisla hai,",
        "aur is step par ek extra shunya **das guna** pay out kar deta us aadmi ko jisne maanga",
        "hi nahi. `422` milega.",
        "",
        "`approvedAmount` na do to poora. `requestedAmount` kabhi overwrite nahi hota — antar",
        "dikhta rehta hai, kyunki wo baad me kisi ko samjhana pad sakta hai.",
        "",
        "**Split wahin dobara freeze hota hai** — jo paisa asal me hilega wahi block me likha",
        "hona chahiye.",
        "",
        "### Do log ek hi request nahi tay kar sakte",
        "",
        "`status` update filter ka hissa hai. Owner aur outlet manager ek hi request dekh sakte",
        "hain; iske bina dono clicks lagte aur doosra pehle ko chup-chaap mita deta — yaani",
        "grahak ka jawab is par nirbhar karta ki kaun dheema tha. Haarne wale ko `409` milta hai",
        "jo **batata hai kya hua**: *\"already been decided (vendor approved)\"* ya",
        "*\"already gone to Trydood for review\"*. Dono ke aage ke kadam alag hain.",
        "",
        "Hold **laga rehta hai** — paisa abhi bhi wapas jaana hai.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
      ],
    }),

    req({
      name: "Refund reject karo",
      method: "PATCH",
      // ⚠️ Its own refund. Approve above decides `{{refund_request_id}}`, so
      // rejecting that one would be rejecting a settled question.
      segments: ["refunds", "{{rejectable_refund_id}}", "reject"],
      token: VEN,
      body: {"note":"Customer collected the order in full."},
      description: [
        "`note` **zaroori** (min 3 chars). Jab grahak inkaar ko chunauti de, admin ke paas",
        "sameeksha karne ko yahi ek cheez hoti hai — akela *\"rejected\"* har appeal ko phone",
        "call bana deta hai.",
        "",
        "⚠️ Aapka note **grahak ko kabhi nahi dikhta**. Wo staff ke liye hai.",
        "",
        "### `settlementHold` yahin hattta hai",
        "",
        "Refund maangte hi aapke us claim ka paisa har settlement se bahar ho jaata hai. Reject",
        "karne par wo **wapas aa jaata hai**.",
        "",
        "> ⚠️ Ulta utna hi khatarnak hai: **jo hold koi na hataaye wo aapka paisa hamesha ke liye",
        "> har aane wali settlement se bahar kar deta hai — chup-chaap**, kyunki eligibility",
        "> predicate bas match karna band kar deta hai. Koi error nahi aata, koi log nahi. Isiliye",
        "> teeno terminal states (`VENDOR_REJECTED`, `ADMIN_REJECTED`, `CANCELLED`) se release",
        "> bulaya jaata hai — aur `FAILED` / `COMPLETED` se **nahi**: pehle me paisa abhi bhi",
        "> wapas jaana hai, doosre me wo aapka tha hi nahi.",
        "",
        "Ek apwaad: us payment par **chargeback** khula ho to hold nahi hattta. Use hataana",
        "explicit admin action hai — refund ki logic se hataane ka matlab hota wo paisa settle",
        "kar dena jise bank usi waqt wapas kheench raha hai.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
      ],
    }),

    req({
      name: "Ek refund — claim aur timeline ke saath",
      method: "GET",
      segments: ["refunds", "{{refund_request_id}}"],
      token: VEN,
      description: [
        "`refund` · `claim` · **`timeline`** · `viewer`. Timeline har audience ke liye",
        "**banayi** jaati hai, chhaani nahi — kaccha audit row `snapshot` me poora pricing",
        "block rakhta hai (`platformPromoCost` samet) aur `reason` staff ka note hai.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
      ],
    }),

    req({
      name: "Approve karne ki koshish, jab rakam badha rahe ho — 422",
      method: "PATCH",
      // ⚠️ A third, still-undecided refund. Pointed at `{{refund_request_id}}`
      // this returned 422 for "already decided" — the right status for the
      // wrong reason, which is the same as no test at all.
      segments: ["refunds", "{{raise_refund_id}}", "approve"],
      token: VEN,
      body: { approvedAmount: 8100 },
      description:
        'Ek extra shunya das guna pay out kar deta us aadmi ko jisne maanga hi nahi. Jawab naam lekar batata hai: *"The customer asked for ₹400.00. You can approve that or less, not more."*',
      assert: [
        "pm.test(\"HTTP 422\", function () {",
        "  pm.response.to.have.status(422);",
        "});",
        "",
        "pm.test(\"failure envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(false);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
      ],
    }),

    req({
      name: "Dusre brand ki refund — 403",
      method: "PATCH",
      segments: ["refunds", "{{other_brand_refund_id}}", "reject"],
      token: VEN,
      body: {"note":"Not ours."},
      description: "Faisla lena padhne se strong action hai, isliye gate usse dheela nahi ho sakta — `SUB_VENDOR` ko dusre outlet ki refund par bhi 403 milta hai.",
      assert: [
        "pm.test(\"HTTP 403\", function () {",
        "  pm.response.to.have.status(403);",
        "});",
        "",
        "pm.test(\"failure envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(false);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
      ],
    }),
  ],
);

// ----------------------------------------------------------------------

const settlementsFolder = folder(
  "20 — Settlements",
  [
    "**Aapka record, aapka form nahi.**",
    "",
    "Settlement par vendor ke liye koi write endpoint nahi hai — na approve, na dispute,",
    "na edit. Ye hamara record hai ki hum aapko kya de rahe hain. Ikhtilaf support se",
    "hota hai, kyunki uske peechhe aksar koi disputed payment hota hai jispar faisla",
    "abhi hua hi nahi.",
    "",
    "Poora flow → `docs/settlement_flow.md`.",
  ].join("\n"),
  [
    req({
      name: "Mere payouts",
      method: "GET",
      segments: ["settlements"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "20" },
        { key: "status", value: "PAID", disabled: true },
        { key: "open", value: "true", disabled: true },
        { key: "from", value: "2026-08-01", disabled: true },
        { key: "to", value: "2026-08-31", disabled: true },
      ],
      token: VEN,
      description: [
        "`SUB_VENDOR` ko is baar **poora brand** dikhta hai, apna outlet nahi: settlement",
        "poore brand ke ek din ka hai, aur outlet se kaat kar dikhane ka matlab ek aisa",
        "figure jo unke dekhe kisi bhi cheez se match nahi karta.",
        "",
        "**Khaali list `404` nahi deti.** Pehle hafte wale brand ke paas koi settlement nahi",
        "hoti — wo bilkul sahi jawab hai, aur use \"kuchh gadbad hai\" jaisa dikhana galat.",
        "",
        "Sort `periodEnd` desc: ye list *\"pichhle hafte ka paisa aaya?\"* ka jawab dene ke",
        "liye padhi jaati hai.",
        "",
        "| Aapko | Aapko nahi |",
        "|---|---|",
        "| `netPayable` · `grossCollected` · `commissionAmount` | `needsRevalidation` |",
        "| `bankSnapshot.accountLast4Digits` · `bankName` | `taintedTransactionIds` |",
        "| `failureReason` (category) | `failureNote` (staff note) |",
        "| `statusLabel` | `approvedBy` · `idempotencyKey` |",
        "",
        "⚠️ Doosre brand ka `brandId` bhejne par **khaali page** milta hai, apne rows nahi.",
        "Scope aur filter kaate jaate hain, upar-neeche rakhe nahi — filter ka \"chal gaya\"",
        "dikhna wahi tareeka hai jisse koi aisi report bana leta hai jo kabhi lagi hi nahi thi.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
        "// ⚠️ `pagination()` answers { total, totalPages, page, limit, data } —",
        "// the rows are one level down. Reading `data` as the array walked the",
        "// page object instead, found none of the fields it was looking for,",
        "// and passed. A vacuous pass is worse than a failure.",
        "const settlementRows = function () {",
        "  const d = pm.response.json().data;",
        "  if (Array.isArray(d)) return d;",
        "  if (d && Array.isArray(d.data)) return d.data;",
        "  return [d && d.settlement ? d.settlement : d];",
        "};",
        "",
        "pm.test(\"hamara margin aur poora bank account nahi bheja jaata\", function () {",
        "  const list = settlementRows();",
        "  pm.expect(list.length, \"koi row hi nahi mili\").to.be.above(0);",
        "  list.forEach(function (row) {",
        "    if (!row) return;",
        "    pm.expect(row, \"needsRevalidation\").to.not.have.property(\"needsRevalidation\");",
        "    pm.expect(row, \"taintedTransactionIds\").to.not.have.property(\"taintedTransactionIds\");",
        "    pm.expect(row, \"failureNote\").to.not.have.property(\"failureNote\");",
        "    pm.expect(row, \"approvedBy\").to.not.have.property(\"approvedBy\");",
        "    pm.expect(row, \"idempotencyKey\").to.not.have.property(\"idempotencyKey\");",
        "    if (row.bankSnapshot) {",
        "      pm.expect(row.bankSnapshot, \"ifscCode\").to.not.have.property(\"ifscCode\");",
        "      pm.expect(row.bankSnapshot, \"accountHolderName\").to.not.have.property(\"accountHolderName\");",
        "      pm.expect(row.bankSnapshot, \"maskedAccountNumber\").to.not.have.property(\"maskedAccountNumber\");",
        "    }",
        "  });",
        "});",
        "",
        "pm.test(\"vendor ko enum nahi, plain language milti hai\", function () {",
        "  settlementRows().forEach(function (row) {",
        "    pm.expect(row.statusLabel, \"statusLabel\").to.be.a(\"string\").and.not.empty;",
        "    pm.expect(row.statusLabel, \"raw enum leaked\").to.not.eql(row.status);",
        "  });",
        "});",
        "",
        "pm.test(\"vendor ko koi action offer nahi hota\", function () {",
        "  settlementRows().forEach(function (row) {",
        "    pm.expect(row.canApprove, \"canApprove\").to.eql(false);",
        "    pm.expect(row.canPay, \"canPay\").to.eql(false);",
        "    pm.expect(row.canRetry, \"canRetry\").to.eql(false);",
        "  });",
        "});",
        "",
        "const first = pm.response.json().data[0];",
        "if (first) pm.collectionVariables.set(\"settlement_id\", first._id);",
      ],
    }),

    req({
      name: "Ek payout, legs ke saath",
      method: "GET",
      segments: ["settlements", "{{settlement_id}}"],
      token: VEN,
      description: [
        "`settlement` · **`legs`** · `timeline` · `viewer`.",
        "",
        "### `legs` — yahan UTR milta hai",
        "",
        "Ek payout do NEFT me bhi ja sakta hai (badi rakam), aur bounce ke baad retry",
        "**nayi leg** banata hai — purani mitayi nahi jaati, taaki record me dono",
        "koshishen bachein. Har leg apna `utr`, `mode`, `paidAt` aur `amount` rakhti hai.",
        "",
        "**UTR wahi ek cheez hai** jo aap teen din baad apne bank statement par dhoondh",
        "sakte hain jab paisa nahi dikhta. Isi liye ek `payoutUtr` field kaafi nahi thi.",
        "",
        "Timeline me `reason` / `performedBy` / `snapshot` **sirf admin ko** jaate hain:",
        "wo notes staff ne staff ke liye likhe hain aur aksar kisi aise dispute ka naam",
        "lete hain jispar faisla hua hi nahi.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
        "// ⚠️ `pagination()` answers { total, totalPages, page, limit, data } —",
        "// the rows are one level down. Reading `data` as the array walked the",
        "// page object instead, found none of the fields it was looking for,",
        "// and passed. A vacuous pass is worse than a failure.",
        "const settlementRows = function () {",
        "  const d = pm.response.json().data;",
        "  if (Array.isArray(d)) return d;",
        "  if (d && Array.isArray(d.data)) return d.data;",
        "  return [d && d.settlement ? d.settlement : d];",
        "};",
        "",
        "pm.test(\"hamara margin aur poora bank account nahi bheja jaata\", function () {",
        "  const list = settlementRows();",
        "  pm.expect(list.length, \"koi row hi nahi mili\").to.be.above(0);",
        "  list.forEach(function (row) {",
        "    if (!row) return;",
        "    pm.expect(row, \"needsRevalidation\").to.not.have.property(\"needsRevalidation\");",
        "    pm.expect(row, \"taintedTransactionIds\").to.not.have.property(\"taintedTransactionIds\");",
        "    pm.expect(row, \"failureNote\").to.not.have.property(\"failureNote\");",
        "    pm.expect(row, \"approvedBy\").to.not.have.property(\"approvedBy\");",
        "    pm.expect(row, \"idempotencyKey\").to.not.have.property(\"idempotencyKey\");",
        "    if (row.bankSnapshot) {",
        "      pm.expect(row.bankSnapshot, \"ifscCode\").to.not.have.property(\"ifscCode\");",
        "      pm.expect(row.bankSnapshot, \"accountHolderName\").to.not.have.property(\"accountHolderName\");",
        "      pm.expect(row.bankSnapshot, \"maskedAccountNumber\").to.not.have.property(\"maskedAccountNumber\");",
        "    }",
        "  });",
        "});",
        "",
        "pm.test(\"legs UTR ke saath aati hain\", function () {",
        "  const legs = pm.response.json().data.legs;",
        "  pm.expect(legs, \"legs\").to.be.an(\"array\");",
        "  legs.forEach(function (leg) {",
        "    pm.expect(leg, \"legNumber\").to.have.property(\"legNumber\");",
        "  });",
        "});",
        "",
        "pm.test(\"staff ka note timeline me nahi hai\", function () {",
        "  pm.response.json().data.timeline.forEach(function (row) {",
        "    pm.expect(row, \"reason\").to.not.have.property(\"reason\");",
        "    pm.expect(row, \"performedBy\").to.not.have.property(\"performedBy\");",
        "    pm.expect(row, \"snapshot\").to.not.have.property(\"snapshot\");",
        "  });",
        "});",
      ],
    }),

    req({
      name: "Statement lines — is payout me kya-kya tha",
      method: "GET",
      segments: ["settlements", "{{settlement_id}}", "transactions"],
      query: [
        { key: "page", value: "1" },
        { key: "limit", value: "50" },
      ],
      token: VEN,
      description: [
        "Alag se paged, kyunki vyast brand ka ek cycle sau-sau rows ka hota hai aur detail",
        "call zyadatar sirf *\"kitna, aur kab\"* ke liye padha jaata hai.",
        "",
        "⚠️ `voucher.platformPromoCost`, `gatewayFee` aur `netReceived` aapko **nahi** milte —",
        "wo hamara margin hai, aur wo **usi sub-document par** baitha hai jispar aapka",
        "`vendorPayable` hai. Isi liye ye faisla ek jagah hota hai.",
        "",
        "`fundsReceivedAt` **`verifiedAt` se alag** hai: pehla matlab Razorpay ne hamare bank",
        "me paisa bheja, doosra matlab grahak ne pay kiya. T+N **pehli** se ginta hai — warna",
        "hum wo paisa baant rahe hote jo abhi aaya hi nahi.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 200\", function () {",
        "  pm.response.to.have.status(200);",
        "});",
        "",
        "pm.test(\"success envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(true);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
        "",
        "pm.test(\"hamara margin statement par nahi hai\", function () {",
        "  // Paginated, like the payout list — the lines are in `data.data`.",
        "  const page = pm.response.json().data;",
        "  const lines = Array.isArray(page) ? page : (page.data || []);",
        "  pm.expect(lines.length, \"statement khaali hai\").to.be.above(0);",
        "  lines.forEach(function (row) {",
        "    pm.expect(row, \"gatewayFee\").to.not.have.property(\"gatewayFee\");",
        "    pm.expect(row, \"netReceived\").to.not.have.property(\"netReceived\");",
        "    if (row.voucher) {",
        "      pm.expect(row.voucher, \"platformPromoCost\").to.not.have.property(\"platformPromoCost\");",
        "    }",
        "  });",
        "});",
      ],
    }),

    req({
      name: "Doosre brand ki settlement — 403",
      method: "GET",
      segments: ["settlements", "{{other_brand_settlement_id}}"],
      token: VEN,
      description: [
        "Detail par `403`, listing par **khaali page** — aur wo farq jaan-boojh kar hai.",
        "",
        "Listing ek sawaal hai (*\"in sharton par kya hai?\"*) aur uska sahi jawab \"kuchh nahi\"",
        "ho sakta hai. Detail ek naam liya hua record hai, aur uska sahi jawab \"aap ise nahi",
        "dekh sakte\" hai.",
      ].join("\n"),
      assert: [
        "pm.test(\"HTTP 403\", function () {",
        "  pm.response.to.have.status(403);",
        "});",
        "",
        "pm.test(\"failure envelope\", function () {",
        "  const b = pm.response.json();",
        "  pm.expect(b.success, \"success flag\").to.eql(false);",
        "  pm.expect(b.message, \"message\").to.be.a(\"string\").and.not.empty;",
        "});",
      ],
    }),
  ],
);

module.exports = { claimsFolder, refundsFolder, settlementsFolder };
