const VOUCHER_USAGE_TYPE = Object.freeze({
  ONCE_PER_USER: "ONCE_PER_USER",
  MULTIPLE: "MULTIPLE",
});

const DISCOUNT_APPLICABLE_ON = Object.freeze({
  SUBTOTAL: "SUBTOTAL",
  FINAL_BILL: "FINAL_BILL",
});

const VOUCHER_SORT_BY = Object.freeze({
  DISTANCE: "DISTANCE",
  NEWEST: "NEWEST",
  EXPIRING_SOON: "EXPIRING_SOON",
  RELEVANCE: "RELEVANCE",
});

const VOUCHER_SORT_ORDER = Object.freeze({
  ASC: "ASC",
  DESC: "DESC",
});

const VOUCHER_APPROVAL_ACTION = Object.freeze({
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PAUSED: "PAUSED",
  RESUMED: "RESUMED",
  ARCHIVED: "ARCHIVED",
  EXPIRED: "EXPIRED",
  PUBLISHED: "PUBLISHED",
});

const VOUCHER_STATUSES = Object.freeze({
  DRAFT: "DRAFT",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  PUBLISHED: "PUBLISHED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  PAUSED: "PAUSED",
  ARCHIVED: "ARCHIVED",
});

const VOUCHER_OFFER_LIMITS = Object.freeze({
  MAX_IMAGES: 5,
  MAX_OFFERS: 10,
  MAX_DISTANCE: 10000,
});

const VOUCHER_DISCOUNT_TYPES = Object.freeze({
  PERCENTAGE: "PERCENTAGE",
  FIXED: "FIXED",
  FLAT: "FLAT",
});

module.exports = {
  VOUCHER_USAGE_TYPE,
  DISCOUNT_APPLICABLE_ON,
  VOUCHER_SORT_BY,
  VOUCHER_SORT_ORDER,
  VOUCHER_APPROVAL_ACTION,
  VOUCHER_STATUSES,
  VOUCHER_OFFER_LIMITS,
  VOUCHER_DISCOUNT_TYPES,
};
