const mongoose = require("mongoose");
const User = require("../../models/User");
const Brand = require("../../models/Brand");
const Customer = require("../../models/Customer");
const { ROLES, LOGIN_TYPES } = require("../../constants");
const { throwError } = require("../../utils");
const { assertAccountAccess } = require("../../helpers/auth");
const { sendOtp } = require("../../services/otps");
const { generateUniqueCustomerId } = require("../../helpers/customers");
const {
  generateUniqueUserId,
  generateReferralCode,
  sanitizeUser,
} = require("../../helpers/users");
const {
  generateUniqueBrandId,
  generateBrandMerchantId,
} = require("../../helpers/brands");

/**
 * Roles a person may bring into existence from this public endpoint.
 *
 * An ADMIN is created by an existing admin through `POST /auth/register`; a
 * SUB_VENDOR by their parent brand through `POST /subBrands/signUp-with-whatsapp`.
 * Both may still **log in** here — they simply cannot be *created* here, which is
 * what stopped `{ whatsappNumber, role: "ADMIN" }` from minting an admin account
 * for anyone who knew the endpoint.
 */
const SELF_SIGNUP_ROLES = Object.freeze([ROLES.CUSTOMER, ROLES.VENDOR]);

/**
 * The side profile each role carries, and the User field that points at it.
 * Keeping this in one place means the create path and the repair path can never
 * disagree about what a role needs.
 */
const ROLE_PROFILES = Object.freeze({
  [ROLES.VENDOR]: {
    model: Brand,
    userField: "brandId",
    build: async (userId, whatsappNumber) => ({
      userId,
      whatsappNumber,
      uniqueId: await generateUniqueBrandId(),
      merchantId: await generateBrandMerchantId(),
    }),
  },
  [ROLES.CUSTOMER]: {
    model: Customer,
    userField: "customerId",
    build: async (userId, whatsappNumber) => ({
      userId,
      whatsappNumber,
      uniqueId: await generateUniqueCustomerId(),
    }),
  },
});

/**
 * Create the User and its role profile as one atomic unit.
 *
 * Previously these were three unguarded writes — `User.create`, then
 * `Brand.create`, then `user.save()` to link them. A failure at the second or
 * third step left a User with no brand, and because the next login found that
 * User and reported `isFirst: false`, the account could never recover: the brand
 * was never going to be created on any later call. A vendor in that state was
 * permanently unable to onboard.
 */
const createUserWithProfile = async ({ whatsappNumber, role }) => {
  const session = await mongoose.startSession();
  let created = null;

  try {
    await session.withTransaction(async () => {
      const [user] = await User.create(
        [
          {
            whatsappNumber,
            role,
            // No password. This account authenticates by OTP; a password only
            // exists once the user chooses one via POST /auth/set-password.
            uniqueId: await generateUniqueUserId(),
            referralCode: await generateReferralCode(),
          },
        ],
        { session },
      );

      const profile = ROLE_PROFILES[role];
      if (profile) {
        const [doc] = await profile.model.create(
          [await profile.build(user._id, whatsappNumber)],
          { session },
        );
        user[profile.userField] = doc._id;
        await user.save({ session });
      }

      created = user;
    });
  } catch (error) {
    // `uniqueId`, `referralCode` and `merchantId` are all generated by
    // read-then-write helpers, so two concurrent signups can pick the same
    // value. The transaction already rolled everything back — surface something
    // the client can act on rather than a raw driver error.
    //
    // The code is checked in three places because a duplicate raised inside a
    // transaction can arrive wrapped: directly, as the cause of a retry
    // failure, or inside `writeErrors` on a bulk insert.
    const isDuplicate =
      error?.code === 11000 ||
      error?.cause?.code === 11000 ||
      error?.writeErrors?.some((e) => e?.code === 11000);

    if (isDuplicate) {
      /**
       * ⚠️ A duplicate here is usually **the other tap winning**, not a failure.
       *
       * Since `user_whatsappNumber_role_unique` exists, two concurrent signups on
       * the same number no longer both insert — one loses on the index. Telling
       * that person *"could not complete signup, please try again"* would be a
       * lie about an account that now exists, and their retry would just race
       * again.
       *
       * So the loser re-reads and continues with the winner's row. Same shape as
       * the claim and refund paths: the index decides who writes, and the one who
       * did not write is handed what the winner made.
       *
       * ⚠️ Before that index, this branch is what four rows on `8210574144` got
       * past — nothing collided, so nothing was refused, and each tap made its
       * own account.
       */
      const winner = await User.findOne({
        whatsappNumber,
        role,
        isDeleted: false,
      });
      if (winner) return winner;

      /**
       * No winner means the collision was on a generated value —
       * `uniqueId`, `referralCode` or `merchantId`, all produced by
       * read-then-write helpers that two callers can land on together. The
       * transaction rolled back, so a retry genuinely is the right advice.
       */
      throwError(409, "Could not complete signup, please try again.");
    }
    throw error;
  } finally {
    await session.endSession();
  }

  return created;
};

/**
 * Bring an account created before the transaction fix back to a usable state.
 *
 * A VENDOR with no `brandId` (or a CUSTOMER with no `customerId`) is the residue
 * of a half-finished signup. Two shapes exist and both are handled: the profile
 * was never created, or it was created and the link back to the User failed. The
 * lookup comes first so a repair never leaves a second orphan behind.
 *
 * Idempotent — a healthy account falls straight through.
 */
const repairRoleProfile = async (user, role, whatsappNumber) => {
  const profile = ROLE_PROFILES[role];
  if (!profile || user[profile.userField]) return user;

  let doc = await profile.model
    .findOne({ userId: user._id, isDeleted: false })
    .select("_id");

  if (!doc) {
    doc = await profile.model.create(
      await profile.build(user._id, whatsappNumber),
    );
  }

  user[profile.userField] = doc._id;
  await user.save();

  console.warn(
    `[auth] repaired missing ${profile.userField} for user ${user._id} (${role})`,
  );

  return user;
};

exports.loginOrSignUpWithWhatsapp = async (body) => {
  let { whatsappNumber, role } = body;
  role = role?.toUpperCase() || ROLES.CUSTOMER;
  whatsappNumber = whatsappNumber?.toLowerCase();

  let user = await User.findOne({ whatsappNumber, role, isDeleted: false });

  // Same gate the auth middlewares use, so a deactivated account is refused with
  // the same status and the same `details.code` at the login screen as it is
  // mid-session. New accounts have nothing to check yet.
  if (user) assertAccountAccess(user);

  if (!user) {
    if (!SELF_SIGNUP_ROLES.includes(role)) {
      throwError(
        403,
        "This account type cannot be created here. Please contact support.",
      );
    }
    user = await createUserWithProfile({ whatsappNumber, role });
  }

  /**
   * Always, not only on the existing-user branch.
   *
   * `createUserWithProfile` can now return a row it did **not** create — the
   * winner of a signup race, handed back after the index refused this request's
   * insert. That row is normally complete, but it was written by another
   * request whose outcome this one cannot see, so assuming it is whole is
   * exactly the assumption that produced orphaned accounts before.
   *
   * Idempotent by design: a healthy account falls straight through.
   */
  user = await repairRoleProfile(user, role, whatsappNumber);

  //  await sendOtp(LOGIN_TYPES.WHATSAPP, whatsappNumber);

  return {
    // Whether this person still has to get through OTP — *not* whether the User
    // row was created on this call. Those came apart whenever an OTP failed to
    // arrive: the row already existed on the retry, so `isFirst` flipped to
    // false and the client sent a returning user down the wrong path even
    // though they had never verified anything.
    isFirst: !user.isMobileVerified,
    // Verified, but the profile (name / dob / email) is still empty. Lets the
    // client route to the profile step without inspecting raw user fields.
    isProfileComplete: Boolean(user.isSignUpCompleted),
    user: sanitizeUser(user),
  };
};
